name: Deploy to AWS

on:
  push:
    branches:
      - main  # كل مرة تعمل push على main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_HOST }} << 'EOF'
          cd ${{ secrets.AWS_PATH }}
          git pull origin main
          npm install --legacy-peer-deps
          npm run build
          pm2 restart ${{ secrets.PROJECT_NAME }}
          EOF