export enum TransactionType {
    TOP_UP = 'TOP_UP',
    PURCHASE_WALLET = 'PURCHASE_WALLET',
    PURCHASE_GATEWAY = 'PURCHASE_GATEWAY',
    GIFT_SENT = 'GIFT_SENT',
    GIFT_RECEIVED = 'GIFT_RECEIVED',
    REFUND_WALLET = 'REFUND_WALLET',
    TRANSFER_WALLET_TO_GATEWAY = 'TRANSFER_WALLET_TO_GATEWAY',
    ADMIN_ADD_BALANCE = 'ADMIN_ADD_BALANCE',
    ADMIN_REMOVE_BALANCE = 'ADMIN_REMOVE_BALANCE',
}

export enum StoreTransactionType {
    REFUND = 'REFUND',
    COMPLETED = 'COMPLETED',
    CANCELED = 'CANCELED',
    SETTLEMENT = 'SETTLEMENT',
    ADMIN_WITHDRAW = 'ADMIN_WITHDRAW',
}