export enum TransactionType {
    TOP_UP = 'TOP_UP',
    PURCHASE_WALLET = 'PURCHASE_WALLET',
    GIFT_SENT = 'GIFT_SENT',
    GIFT_RECEIVED = 'GIFT_RECEIVED',
    REFUND_WALLET = 'REFUND_WALLET',
    PURCHASE_GATEWAY = 'PURCHASE_GATEWAY'
}